experiment_name: 'dummy'          # Name of the experiment
archetecture: [10]           # Number of neurons in each layer
activation: ['relu','relu','sig'] # Activation function for each layer
dom_u: 1                          # Upper bound of the domain
dom_l: -1                          # Lower bound of the domain
npop: 100                         # Number of population
gens: 500                         # Number of generations
mutation: 0.3                     # Mutation rate
last_best: 0                      # Last best value
